name: Tag Push
on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs:
      - test
    if: needs.test.outputs.has-changes == 'true'
    environment: production
    permissions:
      contents: write # To creat the GH Release
      id-token: write # To publish to NPM with provenance
    steps:
      - name: Download Built
        uses: actions/download-artifact@v4
        with:
          name: lib-artifact-${{ github.sha }}
      - name: Prepare NPM for Publish
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
