name: Test
on:
  workflow_call:
    outputs:
      has-changes:
        description: If the distribution are affected from changes
        value: ${{ jobs.build.outputs.uploaded-artifact }}

env:
  MAIN_BRANCH_NAME: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ env.MAIN_BRANCH_NAME }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npx nx affected -t test

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ env.MAIN_BRANCH_NAME }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npx nx affected -t lint

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ env.MAIN_BRANCH_NAME }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Format
        run: npx nx format:check

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
      - test
      - lint
      - format
    outputs:
      uploaded-artifact: ${{ steps.artifact-upload.outputs.artifact-id != ''}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ env.MAIN_BRANCH_NAME }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx nx affected -t build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          if-no-files-found: warn
          name: lib-artifact-${{ github.sha }}
          path: dist/libs/ng-remote-config
